python analyze_from_logs.py share_all_finetune_ep1_e09f
python analyze_from_logs.py share_all_finetune_ep5_bab0
python analyze_from_logs.py share_all_finetune_ep20_b52a
python analyze_from_logs.py share_all_finetune_ep50_dd8d
python analyze_from_logs.py share_all_finetune_ep100_bba7
python analyze_from_logs.py share_all_finetune_ep200_afc8

python analyze_from_logs.py final_share_all_ep200_f829c584_step_order_every
python analyze_from_logs.py final_share_all_ep200_fcd7bca5_step_order_one
python analyze_from_logs.py final_share_all_ep200_45766df6
python analyze_from_logs.py final_share_all_ep2000_7bdd44dc

python analyze_from_logs.py final_group_stable_partition_g1_508c3fba
python analyze_from_logs.py final_group_stable_partition_g2_ed5ff6d1
python analyze_from_logs.py final_group_stable_partition_g4_d8918f36
python analyze_from_logs.py final_group_stable_partition_g8_6480e0bd
python analyze_from_logs.py final_group_stable_partition_g16_565ce648
python analyze_from_logs.py final_group_stable_partition_g32_e7d2dea0
python analyze_from_logs.py final_group_stable_partition_g64_c42fdedd

python analyze_from_logs.py final_group_sim_g2_3e397f16
python analyze_from_logs.py final_group_sim_g4_6eedc0b0
python analyze_from_logs.py final_group_sim_g8_fd508967
python analyze_from_logs.py final_group_sim_g16_0cba3e44
python analyze_from_logs.py final_group_sim_g32_a82f750a

python analyze_from_logs.py final_partial_sharing_prefix_k0_1a9c0da8
python analyze_from_logs.py final_partial_sharing_prefix_k1_f77ea6a6
python analyze_from_logs.py final_partial_sharing_prefix_k2_2cfa93dd
python analyze_from_logs.py final_partial_sharing_prefix_k3_82be74fc
python analyze_from_logs.py final_partial_sharing_prefix_k4_13dd09a3
python analyze_from_logs.py final_partial_sharing_name_only_conv_a1eeaa8d

python analyze_from_logs.py final_partial_sharing_prefix_ep200_k0_4bfe58ad
python analyze_from_logs.py final_partial_sharing_prefix_ep200_k1_da1dcc44
python analyze_from_logs.py final_partial_sharing_prefix_ep200_k2_ce6cc93d
python analyze_from_logs.py final_partial_sharing_prefix_ep200_k3_bf28dc5a
python analyze_from_logs.py final_partial_sharing_prefix_ep200_k4_accaaacc

python analyze_from_logs.py final_partial_sharing_prefix_k0_9fa72ebb
python analyze_from_logs.py final_partial_sharing_prefix_k1_5aa22e49
python analyze_from_logs.py final_partial_sharing_prefix_k2_d97518fe
python analyze_from_logs.py final_partial_sharing_prefix_k3_ac66d7f4
python analyze_from_logs.py final_partial_sharing_prefix_k4_d6bf931c

python analyze_from_logs.py final_partial_sharing_hp_bn1e-1_5fde412c
python analyze_from_logs.py final_partial_sharing_hp_bn9e-1_d37fa71f
python analyze_from_logs.py final_partial_sharing_hp_sgd_momentum0_dbf22dd3
